-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.abandoned_carts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  session_id text,
  cart_data jsonb NOT NULL,
  total_value numeric,
  reminder_sent_at timestamp with time zone,
  recovered_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT abandoned_carts_pkey PRIMARY KEY (id),
  CONSTRAINT abandoned_carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.addresses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['shipping'::text, 'billing'::text])),
  is_default boolean DEFAULT false,
  first_name text NOT NULL,
  last_name text NOT NULL,
  company text,
  address_line_1 text NOT NULL,
  address_line_2 text,
  city text NOT NULL,
  state_province text NOT NULL,
  postal_code text NOT NULL,
  country text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT addresses_pkey PRIMARY KEY (id),
  CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.admin_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  setting_key text NOT NULL UNIQUE,
  setting_value jsonb,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text])),
  old_data jsonb,
  new_data jsonb,
  changed_fields ARRAY,
  user_id uuid,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.cart_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  variant_id uuid NOT NULL,
  custom_design_id uuid,
  dtf_spec_id uuid,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric NOT NULL,
  customization_price numeric DEFAULT 0,
  total_price numeric DEFAULT ((unit_price + customization_price) * (quantity)::numeric),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  original_price numeric,
  discount_percentage numeric,
  discount_amount numeric,
  CONSTRAINT cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT cart_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT cart_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id),
  CONSTRAINT cart_items_custom_design_id_fkey FOREIGN KEY (custom_design_id) REFERENCES public.custom_designs(id),
  CONSTRAINT cart_items_dtf_spec_id_fkey FOREIGN KEY (dtf_spec_id) REFERENCES public.dtf_print_specs(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  description text,
  image_url text,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  translations jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.custom_designs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  design_file_url text NOT NULL,
  design_file_name text NOT NULL,
  file_size_bytes bigint,
  file_format text CHECK (file_format = ANY (ARRAY['PNG'::text, 'JPG'::text, 'JPEG'::text, 'SVG'::text, 'AI'::text, 'PSD'::text, 'PDF'::text])),
  design_width_inches numeric,
  design_height_inches numeric,
  dpi integer CHECK (dpi >= 150),
  color_count integer,
  has_white_ink boolean DEFAULT false,
  is_approved boolean DEFAULT false,
  approval_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT custom_designs_pkey PRIMARY KEY (id),
  CONSTRAINT custom_designs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.discount_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  description text,
  discount_type text NOT NULL,
  discount_value numeric NOT NULL CHECK (discount_value > 0::numeric),
  minimum_purchase numeric DEFAULT 0 CHECK (minimum_purchase >= 0::numeric),
  maximum_discount numeric,
  usage_limit integer,
  usage_count integer DEFAULT 0,
  is_active boolean DEFAULT true,
  valid_from timestamp with time zone DEFAULT now(),
  valid_until timestamp with time zone,
  applicable_to text DEFAULT 'all'::text CHECK (applicable_to = ANY (ARRAY['all'::text, 'category'::text, 'product'::text, 'variant'::text, 'user'::text])),
  applicable_ids ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  priority integer DEFAULT 0 CHECK (priority >= 0 AND priority <= 100),
  stackable boolean DEFAULT false,
  first_purchase_only boolean DEFAULT false,
  minimum_items integer CHECK (minimum_items IS NULL OR minimum_items > 0),
  excluded_products ARRAY,
  campaign_name text,
  discount_category text CHECK (discount_category IS NULL OR (discount_category = ANY (ARRAY['seasonal'::text, 'clearance'::text, 'new_customer'::text, 'loyalty'::text, 'flash_sale'::text, 'promotional'::text, 'referral'::text, 'other'::text]))),
  user_usage_limit integer DEFAULT 1,
  created_by uuid,
  excluded_categories ARRAY,
  auto_apply boolean DEFAULT false,
  customer_segments ARRAY,
  CONSTRAINT discount_codes_pkey PRIMARY KEY (id),
  CONSTRAINT discount_codes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.discount_usage (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  discount_id uuid,
  user_id uuid,
  order_id uuid,
  amount_saved numeric NOT NULL,
  used_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discount_usage_pkey PRIMARY KEY (id),
  CONSTRAINT discount_usage_discount_id_fkey FOREIGN KEY (discount_id) REFERENCES public.discount_codes(id),
  CONSTRAINT discount_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT discount_usage_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.dtf_print_specs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  design_id uuid NOT NULL,
  placement text NOT NULL CHECK (placement = ANY (ARRAY['front'::text, 'back'::text, 'left_chest'::text, 'right_chest'::text, 'sleeve_left'::text, 'sleeve_right'::text, 'custom'::text])),
  placement_x numeric DEFAULT 0,
  placement_y numeric DEFAULT 0,
  print_width_inches numeric NOT NULL CHECK (print_width_inches > 0::numeric),
  print_height_inches numeric NOT NULL CHECK (print_height_inches > 0::numeric),
  print_quality text DEFAULT 'standard'::text CHECK (print_quality = ANY (ARRAY['standard'::text, 'premium'::text, 'high_definition'::text])),
  special_instructions text,
  estimated_cost numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dtf_print_specs_pkey PRIMARY KEY (id),
  CONSTRAINT dtf_print_specs_design_id_fkey FOREIGN KEY (design_id) REFERENCES public.custom_designs(id)
);
CREATE TABLE public.inventory_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  variant_id uuid NOT NULL,
  order_id uuid,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['sale'::text, 'restock'::text, 'adjustment'::text, 'return'::text, 'cancellation'::text])),
  quantity_change integer NOT NULL,
  quantity_before integer NOT NULL,
  quantity_after integer NOT NULL,
  reason text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_transactions_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id),
  CONSTRAINT inventory_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT inventory_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.newsletter_subscribers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email text NOT NULL UNIQUE,
  user_id uuid,
  is_subscribed boolean DEFAULT true,
  source text,
  preferences jsonb DEFAULT '{"blog": true, "promotions": true, "new_products": true}'::jsonb,
  subscribed_at timestamp with time zone DEFAULT now(),
  unsubscribed_at timestamp with time zone,
  CONSTRAINT newsletter_subscribers_pkey PRIMARY KEY (id),
  CONSTRAINT newsletter_subscribers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  product_id uuid NOT NULL,
  variant_id uuid NOT NULL,
  custom_design_id uuid,
  dtf_spec_id uuid,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric NOT NULL,
  customization_price numeric DEFAULT 0,
  total_price numeric NOT NULL,
  production_status text DEFAULT 'pending'::text CHECK (production_status = ANY (ARRAY['pending'::text, 'design_review'::text, 'approved'::text, 'printing'::text, 'completed'::text])),
  production_notes text,
  created_at timestamp with time zone DEFAULT now(),
  product_name text,
  variant_size text,
  variant_color text,
  variant_sku text,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT order_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id),
  CONSTRAINT order_items_custom_design_id_fkey FOREIGN KEY (custom_design_id) REFERENCES public.custom_designs(id),
  CONSTRAINT order_items_dtf_spec_id_fkey FOREIGN KEY (dtf_spec_id) REFERENCES public.dtf_print_specs(id)
);
CREATE TABLE public.order_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  note text NOT NULL,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_notes_pkey PRIMARY KEY (id),
  CONSTRAINT order_notes_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  order_number text NOT NULL UNIQUE,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'processing'::text, 'printing'::text, 'shipped'::text, 'delivered'::text, 'cancelled'::text])),
  subtotal numeric NOT NULL,
  discount_code_id uuid,
  discount_amount numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  shipping_amount numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'refunded'::text])),
  payment_method text,
  stripe_payment_intent_id text,
  shipping_address jsonb,
  billing_address jsonb,
  tracking_number text,
  notes text,
  estimated_delivery_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  guest_email character varying,
  guest_lookup_code character varying,
  shipping_carrier text CHECK (shipping_carrier IS NULL OR (shipping_carrier = ANY (ARRAY['canada_post'::text, 'purolator'::text, 'ups'::text, 'fedex'::text]))),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT orders_discount_code_id_fkey FOREIGN KEY (discount_code_id) REFERENCES public.discount_codes(id)
);
CREATE TABLE public.payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  stripe_payment_method_id text NOT NULL UNIQUE,
  card_brand text NOT NULL,
  card_last4 text NOT NULL,
  card_exp_month integer NOT NULL,
  card_exp_year integer NOT NULL,
  cardholder_name text NOT NULL,
  billing_address_id uuid,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT payment_methods_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT payment_methods_billing_address_id_fkey FOREIGN KEY (billing_address_id) REFERENCES public.addresses(id)
);
CREATE TABLE public.product_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  date date NOT NULL,
  views integer DEFAULT 0,
  add_to_cart_count integer DEFAULT 0,
  purchase_count integer DEFAULT 0,
  revenue numeric DEFAULT 0,
  CONSTRAINT product_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT product_analytics_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.product_images (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid,
  variant_id uuid,
  image_url text NOT NULL,
  alt_text text,
  is_primary boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  view_type text CHECK (view_type = ANY (ARRAY['front'::text, 'back'::text, 'side'::text, 'detail'::text])),
  display_order integer DEFAULT 0,
  CONSTRAINT product_images_pkey PRIMARY KEY (id),
  CONSTRAINT product_images_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_images_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id)
);
CREATE TABLE public.product_reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  order_item_id uuid,
  user_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title text,
  comment text,
  is_verified_purchase boolean DEFAULT false,
  is_approved boolean DEFAULT true,
  helpful_count integer DEFAULT 0,
  images jsonb DEFAULT '[]'::jsonb,
  admin_response text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT product_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_reviews_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id),
  CONSTRAINT product_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.product_variants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  size text NOT NULL CHECK (size = ANY (ARRAY['XS'::text, 'S'::text, 'M'::text, 'L'::text, 'XL'::text, 'XXL'::text, 'XXXL'::text])),
  color text NOT NULL,
  color_hex text,
  price_adjustment numeric DEFAULT 0,
  inventory_count integer DEFAULT 0 CHECK (inventory_count >= 0),
  low_stock_threshold integer DEFAULT 10,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  sku text UNIQUE,
  translations jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT product_variants_pkey PRIMARY KEY (id),
  CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  category_id uuid,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  short_description text,
  base_price numeric NOT NULL CHECK (base_price >= 0::numeric),
  sku text,
  material text,
  care_instructions text,
  tags ARRAY,
  view_count integer DEFAULT 0,
  purchase_count integer DEFAULT 0,
  average_rating numeric DEFAULT 0,
  review_count integer DEFAULT 0,
  meta_title text,
  meta_description text,
  badge text CHECK (badge = ANY (ARRAY['NEW'::text, 'HOT'::text, 'SALE'::text, 'LIMITED'::text])),
  is_active boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  dtf_compatible boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  primary_image_url text,
  translations jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text,
  avatar_url text,
  phone text,
  date_of_birth date,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text, 'prefer_not_to_say'::text])),
  marketing_consent boolean DEFAULT false,
  preferred_language text DEFAULT 'en'::text,
  total_spent numeric DEFAULT 0,
  total_orders integer DEFAULT 0,
  last_order_date timestamp with time zone,
  is_admin boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.search_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  search_query text NOT NULL,
  result_count integer DEFAULT 0,
  user_id uuid,
  session_id text,
  clicked_product_id uuid,
  search_timestamp timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT search_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT search_analytics_user_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT search_analytics_product_fkey FOREIGN KEY (clicked_product_id) REFERENCES public.products(id)
);
CREATE TABLE public.size_charts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  category_id uuid,
  size text NOT NULL,
  chest_inches numeric,
  waist_inches numeric,
  hip_inches numeric,
  length_inches numeric,
  chest_cm numeric,
  waist_cm numeric,
  hip_cm numeric,
  length_cm numeric,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT size_charts_pkey PRIMARY KEY (id),
  CONSTRAINT size_charts_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.tax_rates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  country_code character varying NOT NULL,
  state_code character varying,
  state_name character varying,
  rate numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tax_type character varying,
  gst_rate numeric,
  pst_rate numeric,
  qst_rate numeric,
  hst_rate numeric,
  CONSTRAINT tax_rates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.translations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_type text NOT NULL CHECK (entity_type = ANY (ARRAY['product'::text, 'category'::text, 'variant'::text])),
  entity_id uuid NOT NULL,
  field_name text NOT NULL,
  language_code text NOT NULL CHECK (language_code = ANY (ARRAY['fr'::text, 'en'::text])),
  translated_text text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT translations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_discount_usage (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  discount_id uuid NOT NULL,
  order_id uuid NOT NULL,
  used_at timestamp with time zone DEFAULT now(),
  discount_amount numeric NOT NULL,
  CONSTRAINT user_discount_usage_pkey PRIMARY KEY (id),
  CONSTRAINT user_discount_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_discount_usage_discount_id_fkey FOREIGN KEY (discount_id) REFERENCES public.discount_codes(id),
  CONSTRAINT user_discount_usage_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.wishlist (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  variant_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wishlist_pkey PRIMARY KEY (id),
  CONSTRAINT wishlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT wishlist_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT wishlist_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants(id)
);